# Generated by Django 2.1.7 on 2019-02-16 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_added_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='buy_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 18, 28, 43, 821065)),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='sku',
            field=models.CharField(default='', max_length=52),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
