# Generated by Django 2.1.7 on 2019-02-16 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_added_extra_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='buy_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 18, 35, 19, 252209)),
        ),
    ]
