# Generated by Django 2.1.7 on 2019-02-23 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_updated_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_no', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=18)),
                ('support_phone', models.CharField(max_length=18)),
                ('sales_phone', models.CharField(max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='buy_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 17, 18, 35, 688237)),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
