# Generated by Django 2.1.7 on 2019-02-23 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Company'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='buy_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 18, 38, 31, 829647)),
        ),
    ]
